@extends('layouts.app')
@section('title', 'UDIN Register')
@section('page-title', 'UDIN Register')

@section('content')
<div class="py-4 space-y-6">
    <div class="flex flex-wrap items-center justify-between gap-3">
        <form method="GET" class="flex items-end gap-2">
            <div>
                <label class="block text-xs text-gray-500 mb-1">Search</label>
                <input type="text" name="q" value="{{ $search }}" placeholder="Client or UDIN…" class="border border-gray-300 rounded-lg px-3 py-1.5 text-sm w-56">
            </div>
            <div>
                <label class="block text-xs text-gray-500 mb-1">Status</label>
                <select name="status" class="border border-gray-300 rounded-lg px-3 py-1.5 text-sm">
                    <option value="">All</option>
                    <option value="generated" @selected($status === 'generated')>Generated</option>
                    <option value="revoked" @selected($status === 'revoked')>Revoked</option>
                </select>
            </div>
            <button class="px-4 py-1.5 bg-navy-600 hover:bg-navy-700 text-white text-sm font-medium rounded-lg">Filter</button>
        </form>
        <a href="{{ route('pramaan.udin.create') }}" class="px-4 py-2 bg-amber-600 hover:bg-amber-700 text-white text-sm font-medium rounded-lg">
            <i class="fa fa-plus mr-1.5"></i>Generate UDIN
        </a>
    </div>

    <div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
        <table class="w-full text-sm">
            <thead class="bg-gray-50 text-gray-500 text-xs uppercase tracking-wider">
                <tr>
                    <th class="text-left px-5 py-2.5">UDIN</th>
                    <th class="text-left px-5 py-2.5">Client</th>
                    <th class="text-left px-5 py-2.5">Document</th>
                    <th class="text-left px-5 py-2.5">Doc Date</th>
                    <th class="text-left px-5 py-2.5">Generated By</th>
                    <th class="text-right px-5 py-2.5">Status</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-50">
                @forelse($udins as $u)
                <tr class="hover:bg-gray-50">
                    <td class="px-5 py-3"><a href="{{ route('pramaan.udin.show', $u) }}" class="text-amber-700 font-mono text-xs font-medium hover:underline">{{ $u->udin }}</a></td>
                    <td class="px-5 py-3 text-gray-900">{{ $u->client_name }}</td>
                    <td class="px-5 py-3 text-gray-600">{{ $u->document_type }}</td>
                    <td class="px-5 py-3 text-gray-500">{{ $u->document_date->format('d M Y') }}</td>
                    <td class="px-5 py-3 text-gray-500">{{ $u->generatedBy->name ?? '—' }}</td>
                    <td class="px-5 py-3 text-right">
                        @if($u->status === 'revoked')
                        <span class="text-xs px-2 py-0.5 rounded-full font-medium bg-red-100 text-red-700">Revoked</span>
                        @else
                        <span class="text-xs px-2 py-0.5 rounded-full font-medium bg-green-100 text-green-700">Generated</span>
                        @endif
                    </td>
                </tr>
                @empty
                <tr><td colspan="6" class="px-5 py-10 text-center text-gray-400">No UDINs registered yet. <a href="{{ route('pramaan.udin.create') }}" class="text-amber-700 hover:underline">Generate your first UDIN</a>.</td></tr>
                @endforelse
            </tbody>
        </table>
        @if($udins->hasPages())
        <div class="p-4 border-t border-gray-100">{{ $udins->links() }}</div>
        @endif
    </div>
</div>
@endsection
