@extends('layouts.app')
@section('title', $udin->udin)
@section('page-title', 'UDIN Detail')

@section('content')
<div class="py-4 max-w-2xl space-y-6">
    <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
            @if($udin->status === 'revoked')
            <span class="text-xs px-2.5 py-1 rounded-full font-medium bg-red-100 text-red-700">Revoked</span>
            @else
            <span class="text-xs px-2.5 py-1 rounded-full font-medium bg-green-100 text-green-700">Generated</span>
            @endif
            <span class="text-gray-500 text-sm">Registered {{ $udin->created_at->format('d M Y') }}</span>
        </div>
        <div class="flex items-center gap-2">
            @if($udin->status !== 'revoked')
            <a href="{{ route('pramaan.udin.edit', $udin) }}" class="px-4 py-2 border border-gray-300 text-gray-700 text-sm font-medium rounded-lg hover:bg-gray-50"><i class="fa fa-pen mr-1.5"></i>Edit</a>
            <div x-data="{ open: false }">
                <button @click="open = true" class="px-4 py-2 border border-red-200 text-red-600 text-sm font-medium rounded-lg hover:bg-red-50"><i class="fa fa-ban mr-1.5"></i>Revoke</button>
                <div x-show="open" x-cloak class="fixed inset-0 bg-black/30 flex items-center justify-center z-50" @click.self="open = false">
                    <div class="bg-white rounded-xl p-6 w-full max-w-sm">
                        <h3 class="font-semibold text-gray-900 mb-2">Revoke this UDIN?</h3>
                        <p class="text-sm text-gray-500 mb-4">This marks the UDIN as revoked in your register. This action is logged and cannot be undone.</p>
                        <form method="POST" action="{{ route('pramaan.udin.destroy', $udin) }}" class="flex gap-2">
                            @csrf @method('DELETE')
                            <button type="submit" class="flex-1 px-4 py-2 bg-red-600 hover:bg-red-700 text-white text-sm font-semibold rounded-lg">Confirm Revoke</button>
                            <button type="button" @click="open = false" class="px-4 py-2 text-gray-600 text-sm">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
            @endif
        </div>
    </div>

    <div class="bg-white rounded-xl border border-gray-100 shadow-sm p-6">
        <p class="text-xs text-gray-400 uppercase tracking-wider mb-1">Unique Document Identification Number</p>
        <p class="text-2xl font-mono font-bold text-amber-700 tracking-tight break-all">{{ $udin->udin }}</p>
    </div>

    <div class="bg-white rounded-xl border border-gray-100 shadow-sm divide-y divide-gray-50">
        @foreach([
            ['Client', $udin->client_name],
            ['Client PAN', $udin->client_pan ?: '—'],
            ['Document Type', $udin->document_type],
            ['Document Date', $udin->document_date->format('d M Y')],
            ['ICAI Membership No.', $udin->membership_number],
            ['Generated By', $udin->generatedBy->name ?? '—'],
            ['Revoked At', $udin->revoked_at ? $udin->revoked_at->format('d M Y, H:i') : '—'],
        ] as [$label, $value])
        <div class="flex justify-between px-6 py-3 text-sm">
            <span class="text-gray-500">{{ $label }}</span>
            <span class="text-gray-900 font-medium text-right">{{ $value }}</span>
        </div>
        @endforeach
    </div>

    @if($udin->particulars)
    <div class="bg-white rounded-xl border border-gray-100 shadow-sm p-6">
        <p class="text-xs text-gray-400 uppercase tracking-wider mb-2">Particulars</p>
        <p class="text-sm text-gray-700 whitespace-pre-line">{{ $udin->particulars }}</p>
    </div>
    @endif

    <a href="{{ route('pramaan.udin.index') }}" class="inline-block text-sm text-gray-500 hover:text-gray-700"><i class="fa fa-arrow-left mr-1.5"></i>Back to register</a>
</div>
@endsection
