<?php
namespace Database\Seeders;
use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder {
    public function run(): void {
        $plans = [
            // ── ERP Plans ────────────────────────────────────────────────────
            [
                'slug'             => 'erp-lite',
                'name'             => 'Lekhya ERP Lite',
                'app'              => 'lekhya',
                'edition'          => 'erp',
                'tier'             => 'lite',
                'scope'            => 'erp',
                'client_seat_limit'=> 1,
                'user_seat_limit'  => 1,
                'monthly_price'    => 499,
                'annual_price'     => 4990,
                'lifetime_price'   => null,
                'has_trial'        => true,
                'trial_days'       => 14,
                'is_active'        => true,
                'features'         => ['journal','invoices','reports','basic_gst','bank_recon'],
            ],
            [
                'slug'             => 'erp-pro',
                'name'             => 'Lekhya ERP Pro',
                'app'              => 'lekhya',
                'edition'          => 'erp',
                'tier'             => 'pro',
                'scope'            => 'erp',
                'client_seat_limit'=> 1,
                'user_seat_limit'  => 5,
                'monthly_price'    => 1299,
                'annual_price'     => 12990,
                'lifetime_price'   => null,
                'has_trial'        => true,
                'trial_days'       => 14,
                'is_active'        => true,
                'features'         => ['journal','invoices','reports','basic_gst','bank_recon','ai','connector','gst_filing','einvoice'],
            ],
            [
                'slug'             => 'erp-lifetime',
                'name'             => 'Lekhya ERP Lifetime',
                'app'              => 'lekhya',
                'edition'          => 'erp',
                'tier'             => 'lifetime',
                'scope'            => 'erp',
                'client_seat_limit'=> 3,
                'user_seat_limit'  => 10,
                'monthly_price'    => 0,
                'annual_price'     => 0,
                'lifetime_price'   => 24999,
                'has_trial'        => false,
                'trial_days'       => 0,
                'is_active'        => true,
                'features'         => ['journal','invoices','reports','basic_gst','bank_recon','ai','connector','gst_filing','einvoice'],
            ],

            // ── Pramaan (CA Edition) Plans ───────────────────────────────────
            [
                'slug'             => 'pramaan-lite',
                'name'             => 'Lekhya Pramaan Lite',
                'app'              => 'lekhya',
                'edition'          => 'pramaan',
                'tier'             => 'lite',
                'scope'            => 'pramaan',
                'client_seat_limit'=> 10,
                'user_seat_limit'  => 5,
                'monthly_price'    => 999,
                'annual_price'     => 9990,
                'lifetime_price'   => null,
                'has_trial'        => true,
                'trial_days'       => 14,
                'is_active'        => true,
                'features'         => ['journal','invoices','reports','basic_gst','bank_recon','ai','connector','gst_filing','einvoice','udin','compliance_calendar'],
            ],
            [
                'slug'             => 'pramaan-pro',
                'name'             => 'Lekhya Pramaan Pro',
                'app'              => 'lekhya',
                'edition'          => 'pramaan',
                'tier'             => 'pro',
                'scope'            => 'pramaan',
                'client_seat_limit'=> 9999,   // effectively unlimited
                'user_seat_limit'  => 20,
                'monthly_price'    => 2999,
                'annual_price'     => 29990,
                'lifetime_price'   => null,
                'has_trial'        => true,
                'trial_days'       => 14,
                'is_active'        => true,
                'features'         => ['journal','invoices','reports','basic_gst','bank_recon','ai','connector','gst_filing','einvoice','udin','compliance_calendar','audit_forms','dsc','white_label'],
            ],
            [
                'slug'             => 'pramaan-lifetime',
                'name'             => 'Lekhya Pramaan Lifetime',
                'app'              => 'lekhya',
                'edition'          => 'pramaan',
                'tier'             => 'lifetime',
                'scope'            => 'pramaan',
                'client_seat_limit'=> 9999,
                'user_seat_limit'  => 20,
                'monthly_price'    => 0,
                'annual_price'     => 0,
                'lifetime_price'   => 49999,
                'has_trial'        => false,
                'trial_days'       => 0,
                'is_active'        => true,
                'features'         => ['journal','invoices','reports','basic_gst','bank_recon','ai','connector','gst_filing','einvoice','udin','compliance_calendar','audit_forms','dsc','white_label'],
            ],

            // ── Combo Packs ──────────────────────────────────────────────────
            [
                'slug'             => 'combo-sb-erp',
                'name'             => 'SeedhaBill + Lekhya ERP',
                'app'              => 'lekhya',
                'edition'          => 'combo',
                'tier'             => 'pro',
                'scope'            => 'combo',
                'client_seat_limit'=> 1,
                'user_seat_limit'  => 5,
                'monthly_price'    => 1499,
                'annual_price'     => 14990,
                'lifetime_price'   => 29999,
                'has_trial'        => true,
                'trial_days'       => 14,
                'is_active'        => true,
                'features'         => ['journal','invoices','reports','basic_gst','bank_recon','ai','connector','gst_filing','einvoice','seedhabill'],
            ],
            [
                'slug'             => 'combo-sb-pramaan',
                'name'             => 'SeedhaBill + Lekhya Pramaan',
                'app'              => 'lekhya',
                'edition'          => 'combo',
                'tier'             => 'pro',
                'scope'            => 'combo',
                'client_seat_limit'=> 9999,
                'user_seat_limit'  => 20,
                'monthly_price'    => 3499,
                'annual_price'     => 34990,
                'lifetime_price'   => 69999,
                'has_trial'        => true,
                'trial_days'       => 14,
                'is_active'        => true,
                'features'         => ['journal','invoices','reports','basic_gst','bank_recon','ai','connector','gst_filing','einvoice','udin','compliance_calendar','audit_forms','dsc','white_label','seedhabill'],
            ],
            [
                'slug'             => 'combo-suite',
                'name'             => 'Full Suite',
                'app'              => 'lekhya',
                'edition'          => 'combo',
                'tier'             => 'suite',
                'scope'            => 'combo',
                'client_seat_limit'=> 9999,
                'user_seat_limit'  => 50,
                'monthly_price'    => 4999,
                'annual_price'     => 49990,
                'lifetime_price'   => 99999,
                'has_trial'        => true,
                'trial_days'       => 14,
                'is_active'        => true,
                'features'         => ['all'],
            ],
        ];

        foreach ($plans as $plan) {
            Plan::updateOrCreate(['slug' => $plan['slug']], $plan);
        }
    }
}
